// NaiveUI 主题覆盖（对应 ui-design.md §11.5）
import type { GlobalThemeOverrides } from 'naive-ui';
import { tokens } from './tokens';

const c = tokens.color;

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: c.primary,
    primaryColorHover: c.primaryHover,
    primaryColorPressed: c.primaryPressed,
    primaryColorSuppl: c.primary,
    infoColor: c.info,
    infoColorHover: c.infoHover,
    infoColorPressed: '#1E40AF',
    successColor: c.success,
    successColorHover: c.successHover,
    successColorPressed: '#166534',
    warningColor: c.warning,
    warningColorHover: c.warningHover,
    warningColorPressed: '#B45309',
    errorColor: c.danger,
    errorColorHover: c.dangerHover,
    errorColorPressed: '#991B1B',
    bodyColor: c.bgPage,
    cardColor: c.bgCard,
    modalColor: c.bgCard,
    popoverColor: c.bgCard,
    tableColor: c.bgCard,
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontFamily: `Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif`,
    fontFamilyMono: `"JetBrains Mono", "Fira Code", Consolas, "Courier New", monospace`,
    textColor1: c.text1,
    textColor2: c.text2,
    textColor3: c.text3,
    textColorDisabled: c.textDisabled,
    borderColor: c.border,
    dividerColor: c.border,
    placeholderColor: c.text4,
    boxShadow1: tokens.shadow.sm,
    boxShadow2: tokens.shadow.md,
    boxShadow3: tokens.shadow.lg,
  },
  Button: {
    heightMedium: '32px',
    heightLarge: '36px',
    heightTiny: '24px',
    heightSmall: '28px',
    fontWeight: '500',
    borderRadius: '8px',
  },
  DataTable: {
    thColor: '#F9FAFB',
    thColorHover: '#F3F4F6',
    tdColor: '#FFFFFF',
    tdColorHover: '#F9FAFB',
    thFontWeight: '500',
    tdFontSize: '13px',
    thFontSize: '13px',
    borderRadius: '0px',
  },
  Tabs: {
    tabFontSize: '14px',
    tabTextColor: c.text3,
    tabTextColorActive: c.text1,
    tabTextColorHover: c.text2,
    tabBorderColor: c.border,
  },
  Tag: { borderRadius: '999px' },
  Modal: { borderRadius: '12px' },
  Drawer: { borderRadius: '12px 0 0 12px' },
  Input: {
    border: `1px solid ${c.borderStrong}`,
    borderHover: `1px solid ${c.text4}`,
    borderFocus: `1px solid ${c.primary}`,
    borderError: `1px solid ${c.danger}`,
    borderRadius: '6px',
    heightMedium: '32px',
    heightLarge: '36px',
  },
  Select: {
    border: `1px solid ${c.borderStrong}`,
    borderHover: `1px solid ${c.text4}`,
    borderFocus: `1px solid ${c.primary}`,
    borderRadius: '6px',
  },
  Pagination: {
    itemColorActive: c.primary,
    itemColorActiveHover: c.primaryHover,
    itemTextColorActive: '#FFFFFF',
  },
  Progress: { railColor: c.border },
  Scrollbar: { color: '#D1D5DB' },
  Switch: {
    railColor: c.textDisabled,
    railColorActive: c.primary,
  },
};
